# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [9]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
# print dimension
A.ndim

2

In [4]:
# print shape
A.shape

(3, 5)

In [7]:
# print size
A.itemsize

4

In [6]:
# print datatype
A.dtype.name

'int32'

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [8]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [22]:
# elementwise subtraction
B - C

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [23]:
# elementwise multipication
B * C

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [39]:
# matrix multiplication
B @ C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [40]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
# elementwise exponent
np.exp(B)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [49]:
# calc min value in matrix
B.min()

1

In [52]:
# calc min of each row 
B.min(axis=1)

array([1, 4, 7])

In [53]:
# calc min of each column
B.min(axis=0)

array([1, 2, 3])

In [54]:
# find index value for min value in matrix
np.argmin(B)

0

In [56]:
# find index value for min value in each row
np.argmin(B, axis=0)

array([0, 0, 0], dtype=int64)

In [57]:
# calc sum for all elements
B.sum()

45

In [60]:
# calc mean for each column
np.mean(B, axis=1)

array([2., 5., 8.])

In [61]:
# cal median for each column
np.median(B, axis=1)

array([2., 5., 8.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [62]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [67]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

The missing indices are considered complete slices.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [68]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [69]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [73]:
# iterating through the array elementwise
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [83]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Answer: 

Variabel: "a" creates a 1 dimensional array with 30 elements. 

Variabel: "b" calls a function and reshapes the array from the specified tupple ((2, 3, -1)).

 2: 2 layers

 3: 3 rows

-1: 5 columns. -1 tells numpy to automatically calculate the third dimension based on the total numbers of elements.
To calc it: 30/(2x3) = 5

3 axes array usually means that it has 3 dimensions. 

1. depth or z
2. row or x
3. column or y

While x, y, z can be visualized in a cordinate system. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [84]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [85]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [87]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [16]:
def add_mult_matrices(a, b, operation):
    
    # Check if numpy array
    if not isinstance(a, np.ndarray) or not isinstance(b, np.ndarray):
        raise ValueError("a and b must be numpy arrays")
    
    # Check for operation
    if operation not in ["add", "multiply"]:
        raise ValueError("Operation must be either add or multiply")
    
    # Addition
    if operation == "add":
        if a.shape != b.shape:
            raise ValueError("matrices must be the same size")
        return a + b 
    
    # Multiply
    elif operation == "multiply":
        if a.shape[1] != b.shape[0]:
            raise ValueError("A column must be equal to B rows")
        return np.dot(a, b)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

try:
    result_add = add_mult_matrices(a, b, "add")
    print("Addition result:\n", result_add)

    result_multiply = add_mult_matrices(a, b, "multiply")
    print("Multiplication result:\n", result_multiply)

except ValueError as error:
    print(error)

Addition result:
 [[ 6  8]
 [10 12]]
Multiplication result:
 [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

### 10.1.1

In [21]:
# a
x = np.arange(4,3)
x.ndim

1

In [24]:
# b
x = np.array([4,3])
result = 5 * x
print(result)

[20 15]


In [25]:
# c
x = np.array([4,3])
result = 3*x
print(result)

[12  9]


In [27]:
# d
x = np.array([4,3])
result = 5*x + 3*x
print(result)

[32 24]


In [28]:
# e 
x = np.array([4,3])
result = 8*x
print(result)

[32 24]


In [29]:
# f 
x = np.array([4,3])
result = 4*x - x
print(result)

[12  9]


In [31]:
# g 
x = np.array([4,3])
x_transposed = x.T
x_transposed.ndim

1

In [35]:
# h 
x = np.array([4,3])
result = x + x.T
print(result)

[8 6]


In [37]:
# i
x = np.array([4,3])
norm = np.linalg.norm(x)
print(norm)

5.0


### 10.1.2

In [38]:
# a
v = np.array([3,7,0,11])
v.ndim

1

In [39]:
# b
v = np.array([3,7,0,11])
result = 2*v
print(result)

[ 6 14  0 22]


In [41]:
# c
v = np.array([3,7,0,11])
result = 5*v + 2*v
print(result)

[21 49  0 77]


In [42]:
# d 
v = np.array([3,7,0,11])
result = 4*v - 2*v
print(result)

[ 6 14  0 22]


In [45]:
# e 
v = np.array([3,7,0,11])
v_transposed = v.T
v_transposed.ndim

1

In [46]:
# f 
v = np.array([3,7,0,11])
norm = np.linalg.norm(v)
print(norm)

13.379088160259652


### 10.1.3

In [52]:
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])

# a
norm = np.linalg.norm(v1)
print("norm of v1:\n", norm)

# b 
result = v1 - v2
print("result of v1 - v2:\n", result)
norm_result = np.linalg.norm(result)
print("II v1 - v2 II =\n", norm_result)



norm of v1:
 7.14142842854285
result of v1 - v2:
 [2 0 0 4]
II v1 - v2 II =
 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### 10.2.1

In [55]:
A = np.array([[2, 1, -1],
              [1, -1, 1]])

B = np.array([[4, -2, 1],
              [2, -4,-2]])

C = np.array([[1, 2],
              [2, 1]])

D = np.array([[3, 4],
              [4, 3]])

E = np.array([[1],
              [2]])

I = np.array([[1, 0],
              [0, 1]])

In [56]:
# a
result_A = 2*A
print(result_A)

[[ 4  2 -2]
 [ 2 -2  2]]


In [57]:
# b 
result_B = B - 2*A
print(result_B)

[[ 0 -4  3]
 [ 0 -2 -4]]


In [58]:
# c
result_C = 3*C - 2*E
print(result_C)

[[ 1  4]
 [ 2 -1]]


In [59]:
# d
result_D = 2*D - 3*C
print(result_D)

[[3 2]
 [2 3]]


In [60]:
# e 
result_E = D.T + 2*D
print(result_E)

[[ 9 12]
 [12  9]]


In [61]:
# f 
result_F = 2*C.T - 2*D.T
print(result_F)

[[-4 -4]
 [-4 -4]]


In [ ]:
# g
result_G = A.T - B
print(result_G)

# returns error due to dim missmatch = not defined

In [ ]:
# h
result_H = A @ C
print(result_H)

# returns error due to dim missmatch = not defined

In [68]:
# i
result_I = C @ D 
print(result_I)

[[11 10]
 [10 11]]


In [69]:
# j
result_J = C @ B
print(result_J)

[[  8 -10  -3]
 [ 10  -8   0]]


In [70]:
# k
result_K = C @ I
print(result_K)

[[1 2]
 [2 1]]


In [71]:
# l
result_L = A @ B.T
print(result_L)

[[5 2]
 [7 4]]


### 10.2.2

In [73]:
A = np.array([[2, 3, 4],
              [5, 4, 1]])

result = A @ A.T
print(result)

[[29 26]
 [26 42]]


### 10.2.3

In [78]:
A = np.array([[1, 2],
              [2, 4]])

B = np.array([[2, 1],
              [1, 3]])

C = np.array([[4, 3],
              [0, 2]])

AB = A @ B
AC = A @ C

equal_check = np.array_equal(AB, AC)
print(AB)
print()
print(AC)
print()
print("AB = AC:", equal_check)

not_equal = np.array_equal(B, C)
print("B = C:", not_equal)

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]

AB = AC: True
B = C: False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [88]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [103]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [104]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  0   1   2 123]


### Above statement is true